global:
  domain: localhost
  useHTTPS: false
  useSingleSSLFile: false
  sslCertificateLocation: ""
  sslKeyLocation: ""
  sslSingleFileLocation: ""
  isEncryptedSSLFile: false
  sslPassword: ""
  userKey: ""
  port: 38925
  user:
    username: ""
    password: ""
  onlineMode: false
  setupComplete: false
  publicDomain: null
  publicDomainIsHTTPS: false
  DisableProductAutoRestart: false
products: {}