server:
  # Host includes port if necessary. Do not include when running on :80 or :443
  # example: extension.company.com
  host: infotopicsextension.knaufgroup.com

  # Set custom base path for the extension on a domain “custom-extension” e.g., localhost:8080/custom-extension/
  base: /

license:
  # When not set, it will check for a `license.lic` or `LICENSE` file
  file: ./license.lic