apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: infotopics

configMapGenerator:
  - name: daas-infotopic-cm
    files:
      - config.yml
generatorOptions:
  disableNameSuffixHash: true 

images:
  - name: acrfalconnppltweu001.azurecr.io/infotopics/extensions/super-tables-enterprise
    newTag: 5.5.0
  - name: acrfalconnppltweu001.azurecr.io/infotopics/extensions/power-kpis-enterprise
    newTag: 3.5.1
  - name: acrfalconnppltweu001.azurecr.io/infotopics/extensions/hierarchy-filter-enterprise
    newTag: 1.15.12