apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: infotopics
# namespace: default

images:
  - name: acrfalconnppltweu001.azurecr.io/infotopics/extensions/extension-manager
    newTag: "1.4"
  - name: nginx
    newName: acrfalconnppltweu001.azurecr.io/np-plt/nginx
    newTag: "1.29"

patches:
  - target:
      kind: Ingress
      name: extensions-manager-private-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: np.infotopicsextension.knaufgroup.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: np.infotopicsextension.knaufgroup.com
      - op: replace
        path: /spec/tls/0/secretName
        value: infotopics-np-domain
  - target:
      kind: Ingress
      name: extensions-manager-public-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: np.infotopicsextension.knaufgroup.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: np.infotopicsextension.knaufgroup.com
      - op: replace
        path: /spec/tls/0/secretName
        value: infotopics-np-domain