apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: infotopics
# namespace: default

configMapGenerator:
  - name: cm-super-tables
    files:
      - config.yml=config_maps/super-tables.yml
generatorOptions:
  disableNameSuffixHash: true 

images:
  - name: acrfalconnppltweu001.azurecr.io/infotopics/extensions/extension-manager
    newTag: "1.0.0"

patches:
  - target:
      kind: Ingress
      name: ingress-extensions-private
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: np.falcon-security.knaufgroup.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: np.falcon-security.knaufgroup.com
      - op: replace
        path: /spec/tls/0/secretName
        value: infotopics-server-tls
  - target:
      kind: Ingress
      name: ingress-extensions-public
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: np.falcon-security.knaufgroup.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: np.falcon-security.knaufgroup.com
      - op: replace
        path: /spec/tls/0/secretName
        value: infotopics-server-tls