server {
    listen 80;
    server_name _;
    location /super-tables {
        proxy_pass http://infotopics-ext-super-tables-svc:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        try_files $uri $uri/ /index.html;
    }
    location / {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}