apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-power-kpis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-power-kpis
  template:
    metadata:
      labels:
        app: deployment-power-kpis
    spec:
      containers:
      - image: acrfalconnppltweu001.azurecr.io/infotopics/extensions/power-kpis-enterprise:3.5.1
        imagePullPolicy: Always
        name: deployment-power-kpis
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /app/config.yml
            subPath: config.yml
      volumes:
        - name: config-volume
          configMap:
            name: cm-power-kpis
            items:
              - key: config.yml
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: svc-power-kpis
spec:
  selector:
    app: deployment-power-kpis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
