apiVersion: apps/v1
kind: Deployment
metadata:
  name: infotopics-extension-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infotopics-extension-manager
  template:
    metadata:
      labels:
        app: infotopics-extension-manager
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - infotopics-extension-manager
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: acrfalconnppltweu001.azurecr.io/infotopics/extensions/extension-manager:1.0.0
        command: ["./aft-extensions-manager-linux"]
        args:  ["--port", "38925"]
        imagePullPolicy: Always
        name: infotopics-extension-manager
        readinessProbe:
          httpGet:
            path: /
            port: 38925
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 38925
          initialDelaySeconds: 10
          periodSeconds: 20
        ports:
        - containerPort: 38925
        volumeMounts:
          - name: aft-ext-pv
            mountPath: /app/AFT Extension Manager
      volumes:
        - name: aft-ext-pv
          persistentVolumeClaim:
            claimName: infotopics-extension-manager-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upgrader-extension-manager
spec:
  replicas: 0
  selector:
    matchLabels:
      app: upgrader-extension-manager
  template:
    metadata:
      labels:
        app: upgrader-extension-manager
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - infotopics-extension-manager
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: upgrader-extension-manager
        volumeMounts:
          - name: aft-ext-pv
            mountPath: /app/AFT Extension Manager
      volumes:
        - name: aft-ext-pv
          persistentVolumeClaim:
            claimName: infotopics-extension-manager-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infotopics-extension-manager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: infotopics-extension-manager-svc
spec:
  selector:
    app: infotopics-extension-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 38925
  type: ClusterIP

