apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-super-tables
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-super-tables
  template:
    metadata:
      labels:
        app: deployment-super-tables
    spec:
      containers:
      - image: acrfalconnppltweu001.azurecr.io/infotopics/extensions/super-tables-enterprise:5.5.0
        imagePullPolicy: Always
        name: deployment-super-tables
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /app/config.yml
            subPath: config.yml
      # imagePullSecrets:
      #   - name: acr-secret
      volumes:
        - name: config-volume
          configMap:
            name: infotopic-extensions-cm
            items:
              - key: config.yml
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: svc-super-tables
spec:
  selector:
    app: deployment-super-tables
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
