apiVersion: apps/v1
kind: Deployment
metadata:
  name: daas-infotopic-ext-hierarchy-filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daas-infotopic-hierarchy-filter
  template:
    metadata:
      labels:
        app: daas-infotopic-hierarchy-filter
    spec:
      containers:
      - image: acrfalconnppltweu001.azurecr.io/infotopics/extensions/hierarchy-filter-enterprise:1.15.12
        imagePullPolicy: Always
        name: daas-infotopic-hierarchy-filter
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /app/config.yml
            subPath: config.yml
      volumes:
        - name: config-volume
          configMap:
            name: daas-infotopic-cm-hierarchy-filter
            items:
              - key: config.yml
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: daas-infotopic-ext-hierarchy-filter-svc
spec:
  selector:
    app: daas-infotopic-hierarchy-filter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP