---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/backend-protocol: http
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/super-tables"
    appgw.ingress.kubernetes.io/health-probe-port: "80"
    appgw.ingress.kubernetes.io/health-probe-protocol: "http"
    appgw.ingress.kubernetes.io/waf-policy-for-path: /subscriptions/9e739869-eb3e-483b-83fb-88b4eeea9c08/resourceGroups/rg-falcon-np-plt-weu-001/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/waf-falcon-np-plt-weu-001
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: azure/application-gateway
  name: daas-infotopicss-extensions-private-ingress-st
spec:
  rules:
  - host: np.observability.knaufgroup.com
    http:
      paths:
      - backend:
          service:
            name: daas-infotopics-ext-super-tables-svc
            port:
              number: 80
        path: /super-tables
        pathType: Prefix
  tls:
  - hosts:
    - np.observability.knaufgroup.com
    secretName: infotopics-secondary-server-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/backend-protocol: http
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/super-tables"
    appgw.ingress.kubernetes.io/health-probe-port: "80"
    appgw.ingress.kubernetes.io/health-probe-protocol: "http"
    appgw.ingress.kubernetes.io/waf-policy-for-path: /subscriptions/9e739869-eb3e-483b-83fb-88b4eeea9c08/resourceGroups/rg-falcon-np-plt-weu-001/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/waf-falcon-np-plt-weu-001
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: azure/application-gateway
  name: daas-infotopicss-extensions-public-ingress-st
spec:
  rules:
  - host: np.observability.knaufgroup.com
    http:
      paths:
      - backend:
          service:
            name: daas-infotopics-ext-super-tables-svc
            port:
              number: 80
        path: /super-tables
        pathType: Prefix
  tls:
  - hosts:
    - np.observability.knaufgroup.com
    secretName: infotopics-secondary-server-tls
