---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/backend-protocol: http
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/waf-policy-for-path: /subscriptions/9e739869-eb3e-483b-83fb-88b4eeea9c08/resourceGroups/rg-falcon-np-plt-weu-001/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/waf-falcon-np-plt-weu-001
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: azure/application-gateway
  name: extensions-manager-private-ingress
spec:
  rules:
  - host:
    http:
      paths:
      - backend:
          service:
            name: infotopics-extension-manager-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - 
    secretName:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/backend-protocol: http
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/waf-policy-for-path: /subscriptions/9e739869-eb3e-483b-83fb-88b4eeea9c08/resourceGroups/rg-falcon-np-plt-weu-001/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/waf-falcon-np-plt-weu-001
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: azure/application-gateway
  name: extensions-manager-public-ingress
spec:
  rules:
  - host: 
    http:
      paths:
      - backend:
          service:
            name: infotopics-extension-manager-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - 
    secretName:
