name: Extensions WF

on:
  workflow_dispatch:
  push:

jobs:
  extensions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: Knauf-Group/DCE-Tableau/.github/actions/store_license@extensions
        with:
          license_path: extensions/super-tables-enterprise/app/license.lic
          license_secret: ${{ secrets.TABLEAU_COMBINED_LICENSE }}
      - uses: Knauf-Group/DCE-Tableau/.github/actions/download_extenion@extensions
        with:
          extension_path: test
          extension_destination: dest_path